### ISSUE TITLE
Different conversational history size with the paper's suggestion

### ISSUE THREAD

**Issue by acha21** [qkaren/converse_reading_cmr#10]
The section 6 Experiment Details in your paper said that the maximum length of query is 30. 

I examined your code and found that your pre-processing code truncate the conversational context so that its length is 100 and the training code does not truncate at all.

Am I missing something?

**Comment by qkaren** [comment]
Hi，

in `config.py` we have a line `parser.add_argument('--max_len', type=int, default=30)`, which could control the length of context.

**Comment by Arij-Aladel** [comment]
I think max_doc to truncate the context
