### ISSUE TITLE
No such file of directory 'data/MT-LSTM.pt'

### ISSUE THREAD

**Issue by hamzaLeb** [qkaren/converse_reading_cmr#11]
Hi guys,

When training the model on the processed data the file of the MT-LSTM model is not found. Can someone help please? @qkaren ?

Below is the trace of the error after executing `sh run_san_data_weighted.sh`  

<img width="1440" alt="error_cmr" src="https://user-images.githubusercontent.com/46977672/99797230-26d6ca00-2b2f-11eb-889d-f4fd70d751e4.png">

**Comment by Arij-Aladel** [comment]
Hi Hamza! you download this https://drive.google.com/file/d/1tMCNv8COw0B3wBRkZ_7fI3h6yaSiJ0b-/view
