### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by Arij-Aladel** [qkaren/converse_reading_cmr#12]
Hi!
Thanks for this work and  I would like to ask please about this command:

python dstc.py -c [SUBMISSION] --refs ../data/test.refswhat should be written instead of SUBMISSION

in the readme the 4th step was

Run the following command, where [SUBMISSION] is the submission file you want to evaluate: (same format as the one you submitted on Oct 8.)

What do you mean by  same format as the one you submitted on Oct 8.)??????????!!!!!

**Comment by Arij-Aladel** [comment]
@qkaren

**Comment by qkaren** [comment]
@mgalley Would be the best one to answer your question. Thanks for being patient!

**Comment by mgalley** [comment]
'[SUBMISSION]' is the file to evaluate, whose format is explained earlier ("Prepare your system output for evaluation" section). 

I just updated the README and hopefully that is clearer, but just let us know if that's not the case.

**Comment by Arij-Aladel** [comment]
understand , another question please the full data has the same distribution as toy data or not?

**Comment by mgalley** [comment]
@Arij-Aladel : which toy data are you referring to?

**Comment by Arij-Aladel** [comment]
@mgalley 
https://github.com/qkaren/converse_reading_cmr/tree/master/model/data/processed/toy

**Comment by Arij-Aladel** [comment]
Actually as I tested they have close distribution but I need to ensure more

**Comment by mgalley** [comment]
Sorry, I forgot about that file. Yes, it's a random sample of the full dataset, so the distribution should be fairly close.

**Comment by Arij-Aladel** [comment]
when is_train is zero batcher generates sequences with document length 100 and query length 101 while during training document length 501 and query length is 101 , should not the generator generate the same length of sequences during all stages (train evaluation testing)?
