### ISSUE TITLE
404 Error for RS_2015-01.bz2

### ISSUE THREAD

**Issue by xptree** [qkaren/converse_reading_cmr#4]
When runing `make`, the following wget command encounters 404 not found error.

```
wget https://files.pushshift.io/reddit/submissions/RS_2015-01.bz2 -O reddit/RS_2015-01.bz2 -o logs/RS_2015-01.bz2.log -c
```

More detailed logs:
```
--2019-06-26 09:39:12--  https://files.pushshift.io/reddit/submissions/RS_2015-01.bz2
Proxy request sent, awaiting response... 404 Not Found
2019-06-26 09:39:13 ERROR 404: Not Found.
```

Other files, i.e. data from 2011 to 2014, can be downloaded successfully.

**Comment by xptree** [comment]
According to this page `https://files.pushshift.io/reddit/submissions/`, it seems that from `2015-01`, the file extension changes from bz2 to zst.

**Comment by qkaren** [comment]
We have released the dataset directly. Please download from [here](https://drive.google.com/file/d/1U9F2qf7mA39bPpqcnY0VarnYDQ1ygS6e/view?usp=sharing). You don't have to crawl the data by yourself now.  Thanks!
